---
- name: Set variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_hostname }}.yaml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}_default.yaml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}_default.yaml"
    - "{{ ansible_distribution }}_default.yaml"
    - "{{ ansible_os_family }}_default.yaml"
    - default.yaml
  ignore_errors: yes
