---

- name: Install MySQL
  become: yes
  become_user: root
  become_method: sudo
  apt:
    name: "{{ item }}"
  with_items:
    - python-mysqldb
    - mysql-server

- name: copy .my.cnf
  become: yes
  become_user: root
  become_method: sudo
  template: 
    src: "{{repo.src}}/.my.cnf"
    dest: ~/.my.cnf
    owner: root
    mode: 0600

- name: Start MySQL 
  become: yes
  become_user: root
  become_method: sudo
  service: 
    name: mysql 
    state: reloaded
    enabled: true

  # 'localhost' needs to be the last item for idempotency, see
  # http://ansible.cc/docs/modules.html#mysql-user
- name: mysql root password
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}" 
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 

